# This file contains configuration settings for deploying the application on Netlify.

[build]
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm start"

[[redirects]]
  from = "/*"
  to = "my-react-netlify-app\public\index.html"
  status = 200